<?php
/**
 * Created by PhpStorm.
 * User: macbook
 * Date: 2019-01-25
 * Time: 14:34
 */
include_once ('Circle.php');
class Cylinder extends Circle
{
    public $height;

    function __construct($radius,$height,$color)
    {
        $this->height=$height;
        parent::__construct($radius,$color);
    }

    function setHeight($height)
    {
        $this->height=$height;
    }
    function getHeight()
    {
        return $this->height;
    }

    function calculateArea()
    {
        return parent::calculateArea()*$this->height; // TODO: Change the autogenerated stub
    }
    function calculateVolum()
    {
        return pi() * $this->radius * $this->height;
    }
    public function __toString()
    {
        return "color: ".$this->getColor().",radius: ".$this->getRadius().", chieu cao:".$this->getHeight().",dien tich:".$this->calculateArea().",the tich: ".$this->calculateVolum();
    }
}
?>

